# Generated by Django 6.0.5 on 2026-06-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Vendors',
        ),
    ]
