# Generated by Django 6.0.6 on 2026-06-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
